spring.application.name=demos3
management.endpoints.web.exposure.include=*


aws.region=us-east-1
aws.s3.bucket=transportes-bucket-rene-ambar

aws.access.key=${AWS_ACCESS_KEY_ID}
aws.secret.key=${AWS_SECRET_ACCESS_KEY}
aws.session.token=${AWS_SESSION_TOKEN}
aws.region=us-east-1
aws.s3.bucket=EL_NOMBRE_DE_TU_BUCKET
