spring.application.name=demos3
management.endpoints.web.exposure.include=*


aws.region=us-east-1
aws.s3.bucket=transportes-bucket-rene-ambar

aws.access.key=TU_ACCESS_KEY_AQUÍ
aws.secret.key=TU_SECRET_KEY_AQUÍ
aws.session.token=TU_SESSION_TOKEN_AQUÍ